### ISSUE TITLE
Peers RoleType

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-docs#405]
**Is your proposal related to a problem? Please describe.**
I found no explanation about the peers RoleType, which is an important notion regarding harvesting

```
enum RoleType {
    PeerNode = 1,
    ApiNode = 2,
    DualNode = 3
}
```

**Describe the solution you'd like**
I think a note about that in the following page would be appropriate
 https://nemtech.github.io/guides/accountlink/activating-delegated-harvesting.html

**Additional context**
I forgot what Role Type was not eligible for harvesting, and went to check in the docs

**Comment by dgarcia360** [comment]
@decentraliser Thanks for opening the issue! We could add some more details here about the dual nodes: https://nemtech.github.io/concepts/node.html.

The enum is also described in the REST Gateway documentation, but might be nice as well to add some lines or link redirecting to the main docs: https://nemtech.github.io/symbol-openapi/v0.8.11/#operation/getNodePeers
