### ISSUE TITLE
I think this tx have to be BondedTransaction.

### ISSUE THREAD

**Issue by xembook** [nemtech/symbol-docs#410]
maybe `AggregateTransaction.createBonded` ?

https://github.com/nemtech/symbol-docs/blob/2fa2035840b86a365713c6d78344788d1bbd13bf/source/resources/examples/typescript/metadata/UpdatingMetadataEntriesService.ts#L74

**Comment by dgarcia360** [comment]
Thanks for creating the issue! It will be fixed in the next release.
