### ISSUE TITLE
Replace generationHash for generationHashSeed

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-docs#411]
Due to VRF changes, the generation hash of the first block no longer matches generationHashSeed.
Instead of looking to the first block, the user must retrieve it from ``/node/info``.

- [ ] Change /block/1 generationHash references  to ``/node/info`` generationHashSeed.
- [ ] Change config parameters.

**Comment by fboucquez** [comment]
We are replacing how `repositoryFactory.getGenerationHash()` is resolved. If clients/docs are using that method, they would not need to change the code.
