### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-docs#426]
The idea is to create a new file ``glossary`` and add short definitions for concepts that are unique on Symbol/ blockchain. In the future, we might be able to show these descriptions when the user hovers the word in a small pop up.

Guide:  https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html

**Comment by matthewkim93** [comment]
https://docs.google.com/document/d/1fL55LUEUOytXgNUgJjGLByvM9dO33KkVgwNZwg4gPr8/edit?usp=sharing
