### ISSUE TITLE
config-harvesting.properties  properties doesn't match each other

### ISSUE THREAD

**Issue by vincent-lee90** [nemtech/symbol-docs#444]
![image](https://user-images.githubusercontent.com/10797419/84768625-23cb3100-b007-11ea-963e-0d72e8c4c2ef.png)
![image](https://user-images.githubusercontent.com/10797419/84768662-33e31080-b007-11ea-85e2-337b21311a1f.png)

**Comment by dgarcia360** [comment]
Good catch, thanks for reporting! Just submitted the fix, the new docs will build in a couple of minutes.
