### ISSUE TITLE
Wrong link given for Mosaic

### ISSUE THREAD

**Issue by anubnair** [nemtech/symbol-docs#477]
**Describe the error**
View code links are wrong.

**To Reproduce**
1. Go to 'https://nemtech.github.io/guides/mosaic/creating-a-mosaic.html'
2. Click on 'view code'
3. See error

**Expected behavior**
a link should redirect to https://github.com/nemtech/symbol-docs/blob/main/source/resources/examples/typescript/mosaic/CreatingAMosaic.js

This is happening for all mosaic details -> https://nemtech.github.io/concepts/mosaic.html

**Comment by dgarcia360** [comment]
Thanks @anubnair for opening the issue! We have fixed the URLs in the next documentation release.
