### ISSUE TITLE
Update private network guides to use Symbol Bootstrap

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-docs#496]
The new [Symbol Bootstrap](https://github.com/nemtech/symbol-bootstrap) tool has been approved to be used to run private networks. This tool replaces [catapult-service-bootstrap](https://github.com/nemtech/catapult-service-bootstrap) and [symbol-testnet-bootstrap](https://github.com/nemgrouplimited/symbol-testnet-bootstrap).

This task is to update the docs referencing the new bootstrap tool. **Complete** list of locations to be updated:

- [x] https://docs.symbolplatform.com/guides/network/creating-a-private-test-net.html
- [x] https://docs.symbolplatform.com/references/overview.html#catapult-service
- [x] https://docs.symbolplatform.com/server.html
- [x] https://docs.symbolplatform.com/guides/migration/migrating-from-nem-to-symbol.html
- [x] https://docs.symbolplatform.com/references/overview.html

**Comment by segfaultxavi** [comment]
From Slack, regarding the Configuring Network Properties page:

> @fboucquez 
> About properties, we could probably generate the symbol-doc table from the official config in bootstrap with a unit test
> So updating would be running this unit test, copy and pasting this table
> But either way, you can tune the properties by providing custom presets in bootstrap. So you don't need to change committed code
> @segfaultxavi 
> Autogenerating the properties list sounds really really good
> Where would the descriptions come from?
> @fboucquez 
> I don't think there is a list for them
> If we add and maintain them in bootstrap we can create a command that sysout them for reference

**Comment by fboucquez** [comment]
I've created the feature in bootstrap for the config table generation

https://github.com/nemtech/symbol-bootstrap/issues/21

This feature needs to be prioritized like the other ones.  Unsure if it can be added for this release. Maybe the doc's list needs to be manually updated for now.

**Comment by segfaultxavi** [comment]
I moved the updating of the properties guides to its own issue #516, because that can take some time.
