### ISSUE TITLE
Add EsLint and Prettier to Typescript examples

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-docs#500]
Replace the deprecated `tslint` with `eslint` and `prettier`. 

Exemplo of how to set up can be found in the typescript SDK

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/main/package.json#L16

Travis would need to be updated too. 

Questions: should indentation be 2 instead of 4 so the examples fit better on the docs?

**Comment by segfaultxavi** [comment]
`eslint` and `prettier` have been added for a long while (032d6366d40c911118eccaa6dd3a738fa3534557)
