### ISSUE TITLE
I think minProofSize isn't 10 but 20.

### ISSUE THREAD

**Issue by xembook** [nemtech/symbol-docs#534]
https://github.com/nemtech/symbol-docs/blob/6a517beeecccfd0ced34f63fbed96d944340b18d/source/resources/examples/typescript/secretlock/CrossChainSwap.ts#L50

I think here is

```
const random = crypto.randomBytes(20);
```

because `minProofSize: 20`

https://github.com/nemtech/symbol-bootstrap/blob/04079ecc7982f7410632e711f864934cada792ae/presets/shared.yml#L51

**Comment by segfaultxavi** [comment]
As development progresses it is hard for the docs to keep up.
Thanks a lot for the report!

**Comment by xembook** [comment]
thanks! but I am sorry, one more place 

https://github.com/nemtech/symbol-docs/blob/a77ed9dcb9f41a134b12f2fb9d426ef049613571/source/resources/examples/typescript/secretlock/CrossChainSwap.js#L34

**Comment by segfaultxavi** [comment]
Of course, I forgot the autogenerated js file. My bad.

There's a task to review all examples and make sure they're up to date. We'll fix all these eventually.
