### ISSUE TITLE
Mainnet to erc20

### ISSUE THREAD

**Issue by John555888** [nemtech/symbol-docs#537]
How to convert a mainnet coin in an exchange back to erc20 coin?

**Comment by segfaultxavi** [comment]
You will get more help if you write to the forum:
https://forum.nem.io/
Or the Slack channel:
https://join.slack.com/t/nem2/shared_invite/zt-j0xtyrr8-dJ9p0~Lua4lJx9ZoLbq7mg

These GitHub issues keep track of problems related to the documentation site.
