### ISSUE TITLE
[Guide] Local harvesting through a remote account

### ISSUE THREAD

**Issue by segfaultxavi** [nemtech/symbol-docs#547]
I don't think I was aware of this option, but it should be explained somewhere.

https://nem2.slack.com/archives/C9YKR0EUX/p1608225259204300?thread_ts=1608214610.203500&cid=C9YKR0EUX
https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1608230255400000?thread_ts=1608219011.393000&cid=C015AEQ9ZL2

**Comment by cryptonit** [comment]
now im a bit confused

the solution to my request point to the question?

or does that mean there is no guide available yet and this issue point to that fact and i need to wait?

**Comment by segfaultxavi** [comment]
Currently there are only guides for [local](https://docs.symbolplatform.com/concepts/harvesting.html#local-harvesting) and [delegated](https://docs.symbolplatform.com/concepts/harvesting.html#delegated-harvesting) harvesting.
This ticket is a reminder for me to investigate a possible third option and write a new guide if necessary.

**Comment by cryptonit** [comment]
i dont understand

each node operator will use delegated harvesting

no node operator would use local accounts with addresses that have their private key written in cleartext in local files

so a guide for local harvesting make absolute no sense

but maybe u mean that with local harvesting

but then ur guide need to start at a differnt point

u need to explain how u handle a XYM address in a wallet
how u create a delegated address how u give that delegated address the right to stake ur coins (or whatever its called in symbol)

how u edit the symbol node conf files with the required changes so ur node stake with ur delegated coins

how u edit the conf that ur delegated coins correct make ur node a supernode

how u edit conf that ur node can act as a finallity signer

**Comment by segfaultxavi** [comment]
Thanks to your comments and some internal discussion I have an idea on how to proceed now.
Given than harvesting through a remote account (to avoid exposing your main account in the node's config, which is stored as plain text) is very similar to delegated harvesting I would merge the two guides.
I'll update the delegated harvesting guide (#531) to include remote harvesting. The only difference is Step 4, where you need to edit the config file instead of sending a persistent delegate request.
Node security will be handled in #549.
Supernodes will be handled in #550.
