### ISSUE TITLE
[Guide]How to set up a secure node

### ISSUE THREAD

**Issue by segfaultxavi** [nemtech/symbol-docs#549]
From the discussions in:
- https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1608539867410100
- https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1614352924127600?thread_ts=1614347646.120400&cid=C015AEQ9ZL2

https://github.com/nemtech/symbol-bootstrap/issues/170
https://github.com/nemtech/symbol-bootstrap/pull/178

It should explain how to enable remote harvesting (#547).

It should explain how to do everything from a **cold wallet** (an account private key stored offline):
- Signing transactions (link to #432)
- Generating certificates

It should also explain common security precautions to take on the server (unrelated to Symbol) like properly configuring a firewall or setting the file access flags to `600`.

It should explain the `--password` option in bootstrap.

More info on offline symbol-cli: https://www.notion.so/CLI-offline-txs-create-collect-announce-469a8d3c48bb42df898da73985bfcbb3

A similar guide: https://nemlog.nem.social/blog/58323

**Comment by fboucquez** [comment]
There are notes from a conversation I had with a node owner. 

He was thinking about extracting the private key from the ledger which I didn't recommend.  

So:

How to create a node from a "wealthy" hardware wallet (opted in or not opted in).

What I would do

1. Create the node configuration with all new generated accounts. (bootstrap config command)
2. Send 100 XYM from the ledger to the new main account (to pay for the link fees below).
3. Link all the Voting, Remote, VRF keys to the main account (bootstrap link)
4. Convert the main account to a multisig one where the cosigner is the ledger account.  A 1-1 multi sig would do. (Via symbol desktop wallet, I have not tried this but it should be possible)
5. Send a good amount of XYM from the ledger to the multisig account (I would start small, eventually, send the 3m + for voting).
6. Start the node.

Benefits:

- If you lose your main account's private key, you don't lose your tokens as the hacker needs the ledger to cosign.
- You don't need to "buy" a brand new machine/HD and take out the private key from ledger. Ledger is only used to sign/cosign transactions.
- You could have the main, VRF, Voting remote, node private keys stored and encrypted in a file in either your offline, online, or node machine.  If for any reason, the node is lost (and the certificates), you can recreate the whole configuration with the same keys without going to the ledger key extraction anymore (buying a new machine again). Bootstrap has password protection encryption built-in. 

Please validate Xavi.
