### ISSUE TITLE
Add configuration for deploying other language of preview site.

### ISSUE THREAD

**Issue by 44uk** [nemtech/symbol-docs#554]
nemtech/symbol-docs https://github.com/nemtech/symbol-docs/pull/553
When creating PR, it creates preview website. but /ja seems not to be deployed.
https://deploy-preview-553--nemtech.netlify.app/ja
I expected that the deploying setting is on netlify. Could someone update them for next time?

**Comment by segfaultxavi** [comment]
Yeah, this could be very useful. I'll investigate!

**Comment by dgarcia360** [comment]
On Netlify, you can change the build command to ``make alldocs``, which also builds the Japanese version.
This change will double the build time.

![image](https://user-images.githubusercontent.com/9107969/103476111-d8ae1b00-4daa-11eb-8dad-b3f5c351176f.png)

**Comment by segfaultxavi** [comment]
@44uk This has now been implemented, all languages are available in PR previews. Thanks for the suggestion!
And thanks @dgarcia360!
