### ISSUE TITLE
new phone can't login

### ISSUE THREAD

**Issue by wonnicn** [nemtech/symbol-docs#561]
The new mobile phone can't login. After scanning QR code and entering the password, the input method does not disappear and can't login.

**Comment by wonnicn** [comment]
![image](https://user-images.githubusercontent.com/14865901/104022517-ba5d7a80-5203-11eb-9b9c-966f86c5b874.png)
the next key not work.

**Comment by wonnicn** [comment]
![image](https://user-images.githubusercontent.com/14865901/104023061-74ed7d00-5204-11eb-97bd-2bd5e25ae354.jpeg)
The next key not work.

**Comment by segfaultxavi** [comment]
You will get better answers by posting this issue in the right repository:
https://github.com/nemgrouplimited/symbol-mobile-wallet
