### ISSUE TITLE
Address with a hyphen when creating a simple transaction in Symbol desktop wallet

### ISSUE THREAD

**Issue by moe8ius** [nemtech/symbol-docs#574]
When I creating a simple transaction in Symbol desktop wallet, the address with a hyphen does not allow saving it.

![scr-27jan2021](https://user-images.githubusercontent.com/78087691/105995967-c3cb5b80-60ba-11eb-8647-2af525c2942f.jpg)

Windows 7, Google Chrome

**Comment by segfaultxavi** [comment]
@moe8ius please open this issue in the https://github.com/nemgrouplimited/symbol-desktop-wallet repository. Thanks!

**Comment by moe8ius** [comment]
ok, thanks!
