### ISSUE TITLE
minimum namespace duration is not up to date

### ISSUE THREAD

**Issue by garm01** [nemtech/symbol-docs#584]
The information about the duration of a namespace should be revised to have a current status.
current minimum namespace duration  = 60 days

https://docs.symbolplatform.com/concepts/namespace.html

![Duration_namespaces](https://user-images.githubusercontent.com/46584115/107649849-29ecdc80-6c7e-11eb-8092-9c6516bbb567.png)

---

https://docs.symbolplatform.com/guides/network/configuring-network-properties.html#config-network-properties

![Duration_namespaces2](https://user-images.githubusercontent.com/46584115/107650309-a1bb0700-6c7e-11eb-9589-7409934fae93.png)

**Comment by segfaultxavi** [comment]
The actual minimum namespace duration is 30 days, the documentation is correct. The problem is on the Wallet and it's been tracked already in https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1208

But thanks to your report I remembered to update the property tables. Thanks!
