### ISSUE TITLE
How to sign and verify messeges on the wallet UI?

### ISSUE THREAD

**Issue by konashevich** [nemtech/symbol-docs#598]
There is a statemnet here https://docs.symbolplatform.com/concepts/cryptography.html:
"Messages can be signed using a private key, producing 512-bit (64 byte) signatures."

My question is "how"?
I looked thorugh the wallet but didn't find how to sign and verify messeges.
Please either provide a better explaination on the webpage or better UIX. 

Why I am asking?
I was going to include in a lesson with students this exercice but it seems I will choose another platfrom for demo purposes. 
Thanks.

**Comment by segfaultxavi** [comment]
The Cryptography concept page is a high-level summary of a few key concepts used in Symbol, it does not go into much detail.

In particular, the messages it refers to are not the general-purpose user messages but the transactions that conform the protocol. Transactions are regularly signed and verified as part of the protocol.
If you look at the programming guides (for example, [Sending encrypted mesages](https://docs.symbolplatform.com/guides/transfer/sending-an-encrypted-message)) you'll see that `sign` operations are common.
However, manually signing and verifying transactions is not available in the Wallet, as this is done internally.

Thanks for the report. I'll rename "messages" to "transactions" in the Cryptography page to avoid confusion. All pages are in the process of being reviewed for consistency.
