### ISSUE TITLE
Transfer Transaction Doc-Improvement 

### ISSUE THREAD

**Issue by Taisam2** [nemtech/symbol-docs#605]
Hi! Taisam here, hopefully this is the right place to post this.
We are working on a mijin project and detected information that should be added to the documentation as a hint. Happened under symbol-sdk: 0.23.3

Problem:
Transfer Transaction on a node has been issued, but could not be viewed on the corresponding block explorer.

Solution:
When a transfer transaction is issued a fee is mandatory, as it does not have IP restriction.

**Comment by segfaultxavi** [comment]
Yeah, this is the right place. Thanks for reporting!

We'll take a look, probably after the launch.

**Comment by 90hacker** [comment]
I also encountered the same problem。
SDK：0.23.2 version。
Interface request return `packet 9 was pushed to the network via /transactions`
The transaction information cannot be viewed in the browser through `hash`

**Comment by segfaultxavi** [comment]
Thanks for the report, there's already a couple of issues dealing with this (https://github.com/nemtech/symbol-docs/issues/575, https://github.com/nemtech/symbol-docs/issues/489) so the docs will eventually explain what is happening in this case.
