### ISSUE TITLE
Unable to select a different node and move my XYM to my Seed Account

### ISSUE THREAD

**Issue by MichalJesse** [nemtech/symbol-docs#609]
**Describe the error**
I am unable to transfer funds.
I am unable to choose a different node.

**To Reproduce**
When I log into my Symbol wallet (version 0.15.1) the app tells me that "This account is obtained by an older derivation. It is recommended that you move the funds to a Seed Account"

When I try to move my XYM from the Opt In Seed Account to my Seed Account 1, the transfer does not take place.
Instead, I see a pop-up window informing me: "The wallet cannot monitor the activities of your account on the Symbol chain. Please try selecting a different node."

I then go to Network settings. However, there is only one node in the List of nodes:
http://api.experimental.symboldev.network:3000

I cannot choose a different node 

**Expected behavior**
I wish to be able to move my XYM from my Opt In Seed Account to my normal Seed Account in my Symbol Wallet.
Also, I expect to be able to delegate funds to harvesting in the future.

**Screenshots**
attached 

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Brave Browser
 - Version [1.21.76]

**Additional context**
My Symbol wallet on my Apple iPhone informs me that "Opt-in has finished. You should update your application to get the latest news." 
There is no mobile update for my Symbol wallet (mobile version). This mobile app does not let me do anything beyond this initial screen. Will this change? Will I be able to use my mobile Symbol wallet for transactions?
![IMG_6116](https://user-images.githubusercontent.com/80598717/111298737-66ca3b80-864f-11eb-8b78-ffddc7b7a209.jpg)
![IMG_6117](https://user-images.githubusercontent.com/80598717/111298738-6762d200-864f-11eb-8bcb-4690eb65cf18.jpg)
![IMG_6118](https://user-images.githubusercontent.com/80598717/111298745-6893ff00-864f-11eb-8ef5-ee7e9bdd3235.PNG)

**Comment by segfaultxavi** [comment]
Please open this issue in the https://github.com/nemgrouplimited/symbol-desktop-wallet repository.

**Comment by MichalJesse** [comment]
Xavi, I need help.

I do not know what to do...

Michal Valco

Am Di., 16. März 2021 um 12:28 Uhr schrieb Xavi Artigas <
***@***.***>:

**Comment by segfaultxavi** [comment]
**The Symbol network has not launched yet**. The wallet is not fully operative, and there is only one node to choose from.
Don't worry.

For more information, please log the issue in the Wallet repository, or join the Telegram chat:
https://docs.symbolplatform.com/contribute/community.html
