### ISSUE TITLE
Airdrop 

### ISSUE THREAD

**Issue by ghost** [nemtech/symbol-docs#610]
Symbol out of the building (XYM) I participated in the airdrop was writing will be Snapshot at 3:00 with turkey time 03:50'm Xe (XEM) I sold my Next and now at 7 o'clock says he also received Snapshot please fix this I harmed wait in vain Symbol (XYM) please.

**Comment by Tnrkk** [comment]
..

**Comment by segfaultxavi** [comment]
Please post your issue in the Forum https://forum.nem.io, since it is not a Documentation problem.
