### ISSUE TITLE
モバイルウォレットからのハーベスト

### ISSUE THREAD

**Issue by toru-umemura** [nemtech/symbol-docs#619]
モバイルウォレットからハーベストを開始したのですがちゃんと動いてるのかが気になり　デスクトップウォレットをダウンロードしてみたら　秘密カギなどがちゃんとリンクされてなくて　ハーベストを開始すらしていませんでしたデスクトップウォレットから停止して　再度ノードを変更してハーベストを開始したら　即有効になり　半日後には、報酬をいただけました
おそらくモバイル版だけでは、ハーベストを開始する事は、できない状態だと思います
**Describe the error**
A clear and concise description of what the error is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by segfaultxavi** [comment]
Please open this issue in the Wallet repository:
ウォレットリポジトリでこの問題を開いてください：
https://github.com/nemgrouplimited/symbol-desktop-wallet/issues
