### ISSUE TITLE
symbol-cli account generate

### ISSUE THREAD

**Issue by soltani68** [nemtech/symbol-docs#621]
**Describe the error**
A clear and concise description of what the error is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by soltani68** [comment]
hi

**Comment by segfaultxavi** [comment]
Hi! What's your problem?

**Comment by soltani68** [comment]
I bought nem before March 12 and did not deposit it in my wallet. What should I do now?

**Comment by soltani68** [comment]
my dear friend
I bought nem before March 12 at coinex
I wanted to know if I can transfer it to TOMIC now and OPT IN or if it 's over and if Quinx will give us the prize

**Comment by segfaultxavi** [comment]
If your coins are in a exchange, the exchange should take care of the opt-in and put XYMs in your account automatically.

You will get much better answers from the NEM forums (https://forum.nem.io) since this channel is reserved to discuss documentation issues.
