### ISSUE TITLE
Atomic cross-chain swap between public and private chain

### ISSUE THREAD

**Issue by JonathanOkz** [nemtech/symbol-docs#625]
Hello there

Thank for the great documentation !

There is an error here : https://docs.symbolplatform.com/guides/secretlock/atomic-cross-chain-swap-between-NEM-public-and-private-chain.html

You said :
alice.token is defined in Symbol’s public chain
bob.token is defined in Symbol’s private chain

But Tx1 blocks 10 alice.token in the private chain, however alice.token isn't define in the private chain. So it's imposible.
(other transactions also don't work)

For the atomic swap will be succes, **alice.token will be in the private chain** and **bob.token will be in the public chain**.

Best !

**Comment by segfaultxavi** [comment]
Some of the pages have not been reviewed in a while and might contain errors. I've added this page to the scheduled global review.

Thanks for the report!
