### ISSUE TITLE
Link to Activating Delegated Harvesting from "search" bar is wrong

### ISSUE THREAD

**Issue by ivyfung1** [nemtech/symbol-docs#628]
**Describe the error**
The link to Activating Delegated Harvesting from the "search" bar is wrong.

When I search from the "search" bar, and click on "Activating delegated harvesting", it leads to https://docs.symbolplatform.com/

**Comment by segfaultxavi** [comment]
The search provider is outdated and points to an old page.
There is a redirect in place for exactly this reason, but it was not working.
Fixed now in e6f48dc03ebe0ec7ea13d39ce4edb43356c24636. Thanks!
