### ISSUE TITLE
I did the opt-in on the nem wallet. how can I claim my XYM tokens? I looked everywhere, but nowhere clear instructions. Even "To learn how to move your NIS1 assets to a Symbol account" doesn't give any clue, no instructions whatsoever what to do after the opt-in.

### ISSUE THREAD

**Issue by FordaKimchi** [nemtech/symbol-docs#630]
**Describe the error**
A clear and concise description of what the error is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by segfaultxavi** [comment]
Please use https://forum.nem.io/ for this kind of enquires. This is the developer documentation.
