### ISSUE TITLE
Requirements node.js version should be update

### ISSUE THREAD

**Issue by hitobb** [nemtech/symbol-docs#637]
**Describe the error**

Requirements node.js version is updated from syobolbootstrap v1.04.

https://github.com/nemtech/symbol-bootstrap/releases/tag/v1.0.4

So, this document should be upgrade.

https://docs.symbolplatform.com/guides/network/using-symbol-bootstrap.html

**To Reproduce**

Please check the above two links. 

**Expected behavior**

(1)This document should be upgrade to [node.js version 12 or higher]

(2) [sudo apt install nodejs ] is installed ver 10. so, it should be change to nvm install command.

**Comment by segfaultxavi** [comment]
It has been fixed in 15a3b619b8a1084b29a49d240d169a1d0c506cb1.

Thanks for the report!
