### ISSUE TITLE
How To calculate timestamp value like showed on webpage..

### ISSUE THREAD

**Issue by SalmaBegumJSR** [nemtech/symbol-docs#638]
Greetings..

On a block page

http://explorer.symbolblockchain.io/blocks/XXXX

it sows timestamp value as: 2021-04-17 15:21:47 (1618672907)

but on api response for the same height, timestamp shows as response is : 2819721786

so, how i can get 1618672907 out of 2819721786?

any help please?

thanks in advance

best regards

**Comment by gimer** [comment]
which api returns `2819721786` ?

**Comment by gimer** [comment]
ok, I see, you need to add network EPOCH timestamp:

```
lang=py
delta = datetime.timedelta(milliseconds=2819721786)
result = datetime.datetime.fromtimestamp(1615853185, tz=datetime.timezone.utc) + delta
print(result)
2021-04-17 15:21:46.786000+00:00
```

**Comment by SalmaBegumJSR** [comment]
HI, sir gimer, thanks a lot for your kind help..

but what coding language is that? may i get php code please? or from where i can get it?

and also is.. network EPOCH timestamp is always fixed? or can vary/change?

thanks in advance.. 

best reagrds

**Comment by segfaultxavi** [comment]
The code above is Python. What it means is this:

The Symbol Explorer timestamp (1618672907) is the number of **SECONDS** in the **Unix epoch** (See https://www.epochconverter.com/)
The number returned by the API (2819721786) is the number of **MILLISECONDS** in the **blockchain's Epoch**.

To convert, divide the later by 1000 (to obtain seconds) and add the blockchain's Epoch, which is always **1615853185** (for Symbol's Mainnet).

**Comment by segfaultxavi** [comment]
Yes, you need to filter the receipts based on `targetAddress` using your account's address.
The confusion probably comes from the fact that `targetAddress` uses the Hex representation of an address, and normally addresses use the Base32 representation.
You can use `symbol-cli converter base32ToHexAddress` and `hexToBase32Address` to do the conversion, or the SDK.

This is the documentation repository, though, so you will probably get better answers if you ask in the Slack forum, for example:
https://docs.symbolplatform.com/contribute/community.html

**Comment by segfaultxavi** [comment]
If all questions have been answered, I will close this ticket. This was not the right forum anyway.
