### ISSUE TITLE
Check all node URLs

### ISSUE THREAD

**Issue by segfaultxavi** [nemtech/symbol-docs#639]
The testnet node URLs used so far, for example:
http://api-01.us-east-1.testnet.symboldev.network:3000
do not seem to work anymore. The new node URLs seem to be:
http://ngl-dual-001.testnet.symboldev.network:3000

All text and examples should be updated.

Is this correct, @Wayonb ?

**Comment by Wayonb** [comment]
@segfaultxavi Yes, all the node names were updated as part of latest release.
