### ISSUE TITLE
new xym wallet address issue

### ISSUE THREAD

**Issue by wongyuji** [nemtech/symbol-docs#663]
**Describe the error**
A clear and concise description of what the error is.
I make new xym pc wallet 
but it is not existed (I sent from GateIo to PC wallet, not arrived yet for 5hours)
my xym address is 
NBNNYME7ND6NERB4IZEG7IXFLMEEZ7AWICSA4RI

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by segfaultxavi** [comment]
For support enquires please use:
- Telegram: https://t.me/nemhelpdesk
- Slack: https://join.slack.com/t/nem2/shared_invite/zt-km50fzxd-I8dPNrPEV6cqYVrhyLvrfA
