### ISSUE TITLE
[Guide] Learning RxJS (applied to Symbol-SDK)

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-docs#99]
@jontey proposes on Slack:

> We might have to write our own docs on how to use RxJS6. Most of the examples (that are google-able) is still using RxJS5. Maybe something to consider in #sig-docs

Show the best practices and basics of RxJS6 applied to Symbol SDKs.

## Outline

- Introduction to RXJS
- Why RXJS for blockchain?
- Observables
- Basic operators
    - filter
    - map
    - toArray()
- Advanced operators
    - mergemap (Nesting observables subscription)

## Resources

* [How to write a guide](https://nemtech.github.io/guidelines/writing-a-guide.html)
* [Why ReactiveX for Blockchain SDKs](https://nemlog.nem.social/blog/2648)

**Comment by jontey** [comment]
This section would be good to include/highlight https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#howto-convert-to-pipe-syntax

**Comment by jontey** [comment]
I thought about adding this section in.. But it got too long so I made it a blog post instead. https://thoughts.jonathantey.com/pitfalls-to-avoid-using-rxjs/

**Comment by decentraliser** [comment]
If that can help, here are my beloved 2 ultimate cheatsheets that help(ed) me to go through the learning curve:
[https://www.learnrxjs.io/](https://www.learnrxjs.io/)
[https://rxmarbles.com/](https://rxmarbles.com/)

**Comment by jontey** [comment]
+1 for https://www.learnrxjs.io/
